name: Blog Update

on:
  push:
    paths:
      - 'content/blog/**'
    branches:
      - main

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown python-frontmatter
          
      - name: Install Node.js dependencies
        run: npm ci
        
      - name: Process blog posts
        run: python scripts/process_blog.py
        
      - name: Build project
        run: npm run build
        
      - name: Deploy
        # This step depends on your deployment method
        # For example, if using Vercel:
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
